kind: pipeline
name: default

steps:
- name: build
  image: node:12.6
  commands: 
    - cd ./app
    - npm install
    - npm run build
    - mkdir /drone/src/public
    - mv ./build/* /drone/src/public
- name: publish  
  image: plugins/gh-pages
  settings:
    # upstream_name: https://github.com/alcbotta/drone_react.git
    # target_branch: gh-pages
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    force_push: true
    pages_directory: public/
    temporary_base: tmp/